# NumPy

In [3]:
import numpy as np,pandas as pd

In [7]:
#Q1
my_vector=np.zeros(10)
print(my_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
#Q2
my_vector=np.zeros(10)
my_vector[4]=1
print(my_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [37]:
#Q3
my_array=np.arange(0,9)
my_array=my_array.reshape(3,3)
print(my_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
#Q4
my_array=np.random.random((3,3,3))
my_array

array([[[0.37836637, 0.63404388, 0.50494631],
        [0.17786661, 0.06441121, 0.57198689],
        [0.66107512, 0.02621185, 0.57177805]],

       [[0.60699715, 0.18118797, 0.51883286],
        [0.20737643, 0.46653998, 0.33685424],
        [0.55533581, 0.88921071, 0.89080606]],

       [[0.01286012, 0.62056868, 0.46387132],
        [0.13855437, 0.67814416, 0.4183969 ],
        [0.00179727, 0.23750154, 0.63375546]]])

In [21]:
#Q5
my_arr1=np.ones((5,3))
print(my_arr1)
my_arr2=np.full((3,2),2)
print(my_arr2)
my_prod=np.dot(my_arr1,my_arr2)
print(my_prod)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]
 [6. 6.]
 [6. 6.]
 [6. 6.]]


In [46]:
#Q6
my_arr=np.arange(0,5)
my_arr=np.repeat(my_arr,5)
my_arr=my_arr.reshape(5,5)
print(my_arr)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


In [51]:
#Q7
my_arr=np.random.random((3,3))
print(my_arr)
a=my_arr[0,:].mean()-my_arr[1,:].mean()-my_arr[2,:].mean()
a

[[0.02161417 0.07677976 0.26165195]
 [0.88090314 0.30636273 0.27432313]
 [0.3451247  0.741315   0.28320619]]


-0.8237296745024746

In [74]:
#Q8
my_arr1=np.arange(5,15)
my_arr1=my_arr1.reshape((5,2))
my_arr2=np.arange(100,108)
my_arr2=my_arr2.reshape((2,4))
print('1st array')
print(my_arr1)
print('2nd array')
print(my_arr2)
print('Product array')
print(np.dot(my_arr1,my_arr2))
print('Diagonal of product array')
print(np.dot(my_arr1,my_arr2).diagonal())

1st array
[[ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]
2nd array
[[100 101 102 103]
 [104 105 106 107]]
Product array
[[1124 1135 1146 1157]
 [1532 1547 1562 1577]
 [1940 1959 1978 1997]
 [2348 2371 2394 2417]
 [2756 2783 2810 2837]]
Diagonal of product array
[1124 1547 1978 2417]


In [13]:
#Q9
arr=np.ones(5)
arr[2]=5
arr
from statistics import mode
mode(arr)

1.0

In [105]:
#Q10
vect=np.random.random(10)
vect.sort()
vect

array([0.13149737, 0.22259128, 0.35205463, 0.43562242, 0.49063629,
       0.52109489, 0.7168041 , 0.880274  , 0.908744  , 0.93630038])

# Pandas

In [156]:
#Q11
chipo=pd.DataFrame(pd.read_csv('chipotle.tsv',delimiter='\t'))

In [157]:
#Q12
chipo.head(10)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
6                                                NaN     $1.69   
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75   
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25   
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25

In [150]:
#Q13
len(chipo)

4622

In [129]:
#Q14
print(len(chipo.columns))

5


In [152]:
#Q15
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [105]:
data=chipo[['order_id','quantity']].values

In [107]:
#Q17
from statistics import mode
mode(chipo['order_id'])

926

In [109]:
#Q18
count=0
for i in range(0,len(data)):
    if data[i,0]==926:
        count+=data[i,1]
print(count)

23


In [144]:
#Q19


In [28]:
#Q20
quan=chipo['quantity'].values
quan.sum()

4972

In [158]:
#Q21
chipo['item_price']=chipo['item_price'].str.slice(1,).astype(np.float64)

In [159]:
#Q22
chipo.dtypes

order_id                int64
quantity                int64
item_name              object
choice_description     object
item_price            float64
dtype: object

In [160]:
#Q23
chipo['item_price'].values.sum()

34500.16

In [174]:
#Q24
len(chipo['item_name'].unique())

50

In [171]:
#Q25
int(chipo.describe()['quantity']['count'])

4622

In [164]:
#Q26
chipo.describe()['item_price']['mean']

7.464335785374397